
  export const subjectOption = [
    'Abstract',
    'Animals',
    'Beach',
    'Desert',
    'Fashion',
    'Floral&Botanical',
    'Geometric',
    'Landscapes',
    'Nature',
    'People',
    'Sports',
    'Still Life',
    'Travel&Architecture',
    'Water',
  ];
  export const moodOption = [
    'Moody',
    'Joyful',
    'Soothing',
    'Courageous',
    'Romantic',
    'Nostalgic',
    'Fantasy',
    'Uplifting',
    'Pensive',
  ];
  export const decorOption = [
    'Mid Century Modern',
    'Contemporary',
    'Farmhouse',
    'Bohemian',
    'Scandinavian',
    'Coastal',
    'Industrial',
    'Vintage',
    'Glam',
    'Modern',
    'Art Deco',
    'Traditional',
    'Post Modern',
  ];
  export const artOption = [
    'Abstract',
    'Modern',
    'Impressionist',
    'Minimalist ',
    'Maximalist',
    'Photography',
    'Typography',
    'Folk',
    'Realism',
    'Infographics&Posters',
    'Surrealist',
    'Collage',
    'Landscape',
    'Retro',
    'Pop-Art',
  ];
  export const colorObject = [
    'Black',
    'White',
    'Gray',
    'Brown',
    'Beige',
    'Black&White',
    'Pink',
    'Red',
    'Orange',
    'Yellow',
    'Green',
    'Blue',
    'Purple',
    'Multicolor',
  ];
  export const mediumOption = ['Drawing', 'Mixed Media', 'Photography', 'Graphic', 'Painting'];
  export const orientationOption = ['Horizontal', 'Vertical'];
  export const sizeOption =['1824','2432','3040','3244']